### ISSUE TITLE
 [warning] Failed to connect to "/p2p/...": dialing_self

### ISSUE THREAD

**Issue by benoitc** [helium/erlang-libp2p#173]
I am trying this simple example:
```erlang
-module(testapp1).

-export([echo/0]).


data_dir() ->
  ok = filelib:ensure_dir("data"),
  "data".


swarm(Name) ->
   Opts = [{base_dir, data_dir()},
          {libp2p_nat, [{enabled, false}]}],
  {ok, Pid} = libp2p_swarm:start(Name, Opts),
  ok = libp2p_swarm:listen(Pid, "/ip4/0.0.0.0/tcp/0"),
  Pid.

echo() ->
  Swarm1 = swarm(echo1),
  Swarm2 = swarm(echo2),

  timer:sleep(1000),
  [_Addr1|_] = libp2p_swarm:listen_addrs(Swarm1),
  [Addr2|_] = libp2p_swarm:listen_addrs(Swarm2),

  {ok, Session} = libp2p_swarm:connect(Swarm1, Addr2),

    timer:sleep(1000),
   libp2p_swarm:stop(Swarm1),
   libp2p_swarm:stop(Swarm2).

```

 but I get the following warning messages:

```erlang
1> testapp1:echo().
11:22:21.691 [info] libp2p_nat_server init with [#Ref<0.307704574.4151181315.127969>]
11:22:21.693 [info] libp2p_proxy_server init with [#Ref<0.307704574.4151181315.127969>,10]
11:22:21.703 [warning] nat is disabled
11:22:21.703 [info] Started Listener on ["/ip4/192.168.165.162/tcp/64001"]
11:22:21.713 [info] libp2p_nat_server init with [#Ref<0.307704574.4151181315.128256>]
11:22:21.713 [info] libp2p_proxy_server init with [#Ref<0.307704574.4151181315.128256>,10]
11:22:21.714 [warning] nat is disabled
11:22:21.714 [info] Started Listener on ["/ip4/192.168.165.162/tcp/64002"]
11:22:22.733 [notice] recording observed address "/p2p/112RuZ3qSUiBaQQyGXHyhdnpEnnWWPGveVfsmoS8pn5HKK9C9NZN" "/ip4/192.168.165.162/tcp/64001"
11:22:22.909 [warning] Failed to connect to "/p2p/11275kQ641uRGo1pkQR3VHGWboFeffb1exYt9G9vbdvYDuY9ytQ2": dialing_self
11:22:22.985 [warning] Failed to connect to "/p2p/112Y5XgyCJqp5dNYzeVECoHS3yMwGYa9FcsVatcDomLMihs48myG": dialing_self
11:22:23.977 [error] Session header read failed: enotconn 
```

Is this expected? Wat is this enotconn error?

**Comment by benoitc** [comment]
nevermind I probably need to add a stream handler first. what shoul dI expect if the stream handler is created a connection is set?

**Comment by madninja** [comment]
Hmm.. you'll need to create a stream handler to do anything useful with a session, but you should be able to connect two swarms together without any custom handlers. 

I'm not sure what's wrong here since the unit tests do _exactly_ this setup, but here's a couple of things to try:

1. Could you check on the filesystem to ensure that each swarm had a unique data folder?
2. Try setting the peerbook_connections option to 0 to see if that's what's causing the problem. 

Add the following tuple to the startup opts: 

```{libp2p_group_gossip,
                                         [{peerbook_connections, 0}]
                                        }
```

**Comment by benoitc** [comment]
sorry I missed your answer. I will try later today. To be honest I wouldn't be against a quick and dirty "getting started" doc :)

**Comment by benoitc** [comment]
> 1. Could you check on the filesystem to ensure that each swarm had a unique data folder?

why do they need a data folder btw?

**Comment by madninja** [comment]
A swarm stores its keys in the data folder (unless configured otherwise) as well as it's peer book and any group information that has to persist across restarts/crashes
