### ISSUE TITLE
Implement STUN/TURN style handlers

### ISSUE THREAD

**Issue by Vagabond** [helium/erlang-libp2p#27]
When a libp2p node has bound to a listen address (with reuseaddr) and attempted nat-upnp, it needs to know if either strategy actually *worked*.

We can provide a STUN handler where dialing it tells you what the other side sees your IP/port as (apparently with an XOR on it so evil NATs don't rewrite the packet(?!)) and maybe you send some unique token. The other side then tries to dial your external IP/port and send you the token. If you get it, you know you have a hole punched and you can publish your external IP/port.

If that doesn't work, a TURN handler could be offered (on nodes with a working public address) where you can dial the peer, it gives you back a multiaddr like `/turn/ip4/8.8.8.8/8888/SomeToken`. Other peers can dial this and the TURN server can simply shuttle packets to the session it has with that NAT'd peer. The token allows a quick way to discard dials if they're for an already closed or invalid session.

I think the combination of these 2 strategies, along with #24 and #26, should allow most libp2p nodes to participate in the network.

https://en.wikipedia.org/wiki/STUN
https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT
https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment

**Comment by Vagabond** [comment]
Looks like libp2p calls this 'circuit relay': https://github.com/libp2p/specs/tree/master/relay

**Comment by madninja** [comment]
This library now has a pretty complete implementation of this. Closing the feature in favor of bug requests
