### ISSUE TITLE
add custom transports

### ISSUE THREAD

**Issue by benoitc** [helium/erlang-libp2p#36]
What is the plan to add custom transports? I'm thinking to add support for websockets to the lib but I'm wondering if such support should be internal or via an extrenal app?

**Comment by madninja** [comment]
@benoitc We'll have to add the ability to register transport modules with a swarm. After that, a custom transport could be a third party library

**Comment by madninja** [comment]
hmm.. the websockets add-on for libp2p.io _is_ a separate module and not built into libp2p itself, right?  The separate module is located at: https://github.com/libp2p/js-libp2p-websockets

**Comment by benoitc** [comment]
right. OK I will work on that patch :) thanks!

**Comment by madninja** [comment]
Thanks @benoitc ! I was thinking it'd be similar in approach to `add_connection_handler` in libp2p_swarm. We could add a `add_transport` which registers transports. libp2p_transport would then "resolve" the right one by asking each of the registered transports in order if they handle a given multiaddr

**Comment by madninja** [comment]
@benoitc looksl like we need this ourselves right now to abstract factor out the stun/tun handling into transport_tcp. I'll add the ability to add a transport handler, and when you're ready you can presumably add an external websockets module
