### ISSUE TITLE
Treat rfc6598 addresses (100.64.0.0/10) as non-public

### ISSUE THREAD

**Issue by PaulVMo** [helium/erlang-libp2p#367]
As observed by the community of validator operators, there are several validators and hotspots in the peer book with IP addresses in the 100.64.0.0/10 address. These are non-routable addresses in the shared address space as defined by RFC6598.

The [is_public()](https://github.com/helium/erlang-libp2p/blob/0b8f41be95156d94746a53fd62514f95d0d66f58/src/libp2p_transport_tcp.erl#L374) check for IP addresses currently only considered RFC1918 address (10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0). However there are several other non-routable IP addresses ranges. RFC6598 seems to be the next most common set apart from

**Comment by kellybyrd** [comment]
There are more non-public ranges than just RFC1918 and RFC6598. Many firewalls solve this problem by downloading a [bogon](https://team-cymru.com/community-services/bogon-reference/) list. The list includes RFC1918, RFC6598, the link local addresses, various test ranges, etc.  It also includes ranges that have not been assigned to an ISP or end user yet. The lists are updated periodically, typically once a week or something like this. 

IMO, the minimum would be to use a static copy of the "[The Text Bogon List, Aggregated](https://www.team-cymru.org/Services/Bogons/bogon-bn-agg.txt)"  from  copied from here:  https://team-cymru.com/community-services/bogon-reference/bogon-reference-http/ 

Even better would be to build a mechanism to update that list periodically (1-2 a day at most should be fine, I think my firewall is set to update once a week) and use the "IPv4 Fullbogons" list on that same bogon reference page.

**Comment by Vagabond** [comment]
That's a pretty short list, how often does it realistically change?

**Comment by kellybyrd** [comment]
> That's a pretty short list, how often does it realistically change?

The version of the list he used in the code is just the RFC'd ranges and in ipv4 land, that's really all there is anymore, everything else is allocated. So it's only likely to change when an existing range is changed. So maybe once every few years? But if there is ever ipv6 support than that changes more often.

**Comment by PaulVMo** [comment]
To add, more extensive bogon lists also includes allocated public IPs address blocks that have not been assigned to an ISP. I do not think that is necessary as the larger risk is misconfiguration using private/shared blocks rather than the broader set of allocated but yet to be assigned IPs. Someone would need to intentionally use an unassigned IP which is not really to their advantage in any way. Misconfigure is the more likely scenario.

**Comment by PaulVMo** [comment]
Closed by #368 and #369.
