### ISSUE TITLE
Have swarm_server maintain N open peer connections 

### ISSUE THREAD

**Issue by madninja** [helium/erlang-libp2p#43]
Have the swarm (through a session_agent) maintain a configurable set of connections to randomly selected peers. 

- [x] The configuration would ideally be a module name in the swam options with a simple default. So that applications can supply a more complex one if they have more context to be able to generate a diverse set of peer addresses from the peerbook. 

- [x] When agent detects a disconnected peer connection it should randomly select a new peer address and connect to it.

- [x] Have the session_agent _forget_ an existing connection on a regular schedule. It would then pick a new random address to connect to. The normal session timeout will end up closing the session.

- [x] For the set of open connections also be able to supply the list of stream handlers to start for a newly opened connection.

- [x] The simple policy uses a configuration list of `seed_nodes` passed in as part of #42, and will select a number of (non-stale) nodes from the peerbook and at least one from the list of nodes specified in `seed_nodes`. 

@Vagabond does this capture what we had in mind?

**Comment by Vagabond** [comment]
Yes, I think this sums it up nicely.
