### ISSUE TITLE
Where to have technical discussions about erlang-libp2p?

### ISSUE THREAD

**Issue by dhuseby** [helium/erlang-libp2p#453]
Hello!

My name is Dave and I'm working on libp2p community improvements. Over the last few months the other libp2p implementations have been turning on GH Discussions as a place for contributors and users to ask technical questions. I have been sending PR's to each implementation repo to set up the "new issue" template to include links to the GH discussion forums for technical questions related to the implementation and a link to the community-wide libp2p discussions at https://discuss.libp2p.io/.

The swift-libp2p implementation just recently enabled GH discussion: https://github.com/swift-libp2p/swift-libp2p/discussions

I just landed a PR for their new issue template: https://github.com/swift-libp2p/swift-libp2p/issues/new/choose

Will you please consider enabling GH Discussions for this repo?

Cheers!

**Comment by Vagabond** [comment]
This repo, and the effort behind implementing libp2p in Erlang is currently dormant, unfortunately. I don't expect it to be revived by the company that originally funded the development.

**Comment by dhuseby** [comment]
@Vagabond and @madninja so is nim-libp2p officially "tomb stoned" then? If it is, I think we should change the README.md file to reflect that and to have pointers to the libp2p community forum for anybody interested in taking over maintainership. I'm happy to be added to the list of maintainers for now so that I can facilitate the discussion/recruitment of maintainers. I'm also happy to send a PR to update the README.md with the links and status information.
